BEGIN;

DROP TRIGGER vibetype_private_account_password_reset_verification_valid_until ON vibetype_private.account;
DROP TRIGGER vibetype_private_account_email_address_verification_valid_until ON vibetype_private.account;
DROP FUNCTION vibetype_private.account_password_reset_verification_valid_until;
DROP FUNCTION vibetype_private.account_email_address_verification_valid_until;
DROP TABLE vibetype_private.account;

COMMIT;
