BEGIN;

DROP POLICY account_preference_event_size_delete ON vibetype.account_preference_event_size;
DROP POLICY account_preference_event_size_insert ON vibetype.account_preference_event_size;
DROP POLICY account_preference_event_size_select ON vibetype.account_preference_event_size;

COMMIT;
