name: "Release: Scheduled"

permissions: {}

on:
  schedule:
    - cron: "0 0 * * 6" # Every Saturday at 00:00 AM UTC on the default branch
  workflow_dispatch:

jobs:
  release-schedule:
    name: "Release: Scheduled"
    uses: dargmuesli/github-actions/.github/workflows/release-schedule.yml@298fae1fbc879585a0fc7dbf34e7dee04a0e6b0b # 5.9.1
    permissions:
      contents: read
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      IS_DEBOUNCED: ${{ github.event_name != 'workflow_dispatch' }}
